# Generated by Django 4.1.4 on 2022-12-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_historymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodel',
            name='status',
            field=models.CharField(choices=[('1', 'درحال رسیدگی'), ('2', 'محصول ارسال شده است')], default='1', max_length=50, null=True),
        ),
    ]
