# Generated by Django 4.1.4 on 2022-12-31 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_comment_text'),
        ('accounts', '0007_alter_historymodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymodel',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
