# Generated by Django 4.1.4 on 2022-12-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_historymodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodel',
            name='status',
            field=models.CharField(choices=[('درحال رسیدگی', 'درحال رسیدگی'), ('محصول ارسال شده است', 'محصول ارسال شده است')], default='1', max_length=50, null=True),
        ),
    ]
