# Generated by Django 4.1.4 on 2022-12-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_historymodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymodel',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historymodel',
            name='status',
            field=models.CharField(choices=[('درحال رسیدگی', 'درحال رسیدگی'), ('محصول ارسال شده است', 'محصول ارسال شده است')], default='درحال رسیدگی', max_length=50, null=True),
        ),
    ]
