# Generated by Django 4.1.4 on 2022-12-31 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_comment_text'),
        ('accounts', '0010_historymodel_quantity_alter_historymodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodel',
            name='Datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='historymodel',
            name='get_total_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historymodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='historymodel',
            name='status',
            field=models.CharField(blank=True, choices=[('درحال رسیدگی', 'درحال رسیدگی'), ('محصول ارسال شده است', 'محصول ارسال شده است')], default='درحال رسیدگی', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historymodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
