# Generated by Django 4.1.4 on 2022-12-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTeam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOstadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('work', models.CharField(blank=True, max_length=70, null=True)),
                ('description_me', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=40, null=True)),
                ('specialty', models.CharField(blank=True, max_length=40, null=True)),
                ('description_short', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('telegram', models.TextField(blank=True, null=True)),
                ('instagram', models.TextField(blank=True, null=True)),
                ('whatsapp', models.TextField(blank=True, null=True)),
                ('price1', models.CharField(blank=True, max_length=30, null=True)),
                ('price2', models.CharField(blank=True, max_length=30, null=True)),
                ('price3', models.CharField(blank=True, max_length=30, null=True)),
                ('price4', models.CharField(blank=True, max_length=30, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='myteammodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='myteammodel',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='myteammodel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='myteammodel',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='myteammodel',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='myteammodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='myteammodel',
            name='price1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='myteammodel',
            name='price2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='myteammodel',
            name='price3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='myteammodel',
            name='price4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
