# Generated by Django 4.1.4 on 2022-12-21 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyTeam', '0002_userostadmodel_remove_myteammodel_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTeamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('date', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyTeam.myteammodel')),
            ],
        ),
    ]
