# Generated by Django 4.1.4 on 2022-12-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTeam', '0003_dateteammodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateteammodel',
            name='time',
            field=models.TimeField(),
        ),
    ]
