# Generated by Django 4.1.4 on 2022-12-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTeam', '0004_alter_dateteammodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateteammodel',
            name='is_rezerv',
            field=models.BooleanField(default=False),
        ),
    ]
