# Generated by Django 4.1.4 on 2022-12-21 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyTeam', '0005_dateteammodel_is_rezerv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateteammodel',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='MyTeam.myteammodel'),
        ),
    ]
