# Generated by Django 4.1.4 on 2022-12-24 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyTeam', '0007_dateostadmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateostadmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ostads', to='MyTeam.userostadmodel'),
        ),
    ]
