# Generated by Django 4.1.4 on 2022-12-25 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyTeam', '0008_alter_dateostadmodel_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateOstadModel',
        ),
    ]
