# Generated by Django 4.1.4 on 2022-12-25 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyTeam', '0009_delete_dateostadmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateOstadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('is_rezerv', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyTeam.userostadmodel')),
            ],
        ),
    ]
