# Generated by Django 4.1.4 on 2022-12-25 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyTeam', '0010_dateostadmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RezervTeamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('khadamat', models.CharField(max_length=100)),
                ('is_rezerv', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyTeam.myteammodel')),
            ],
        ),
    ]
