# Generated by Django 4.1.4 on 2022-12-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyTeam', '0014_rename_user_rezervostadmodel_ostad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezervostadmodel',
            name='ostad',
        ),
    ]
