# Generated by Django 4.1.4 on 2022-12-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTeam', '0015_remove_rezervostadmodel_ostad'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervteammodel',
            name='authority',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
