# Generated by Django 4.1.4 on 2022-12-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTeam', '0016_rezervteammodel_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervostadmodel',
            name='authority',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
