# Generated by Django 4.1.4 on 2023-01-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTeam', '0017_rezervostadmodel_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='myteammodel',
            name='darbare_majmoee',
            field=models.TextField(blank=True, null=True),
        ),
    ]
