# Generated by Django 4.1.4 on 2023-01-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTeam', '0018_myteammodel_darbare_majmoee'),
    ]

    operations = [
        migrations.AddField(
            model_name='userostadmodel',
            name='darbare_majmoee',
            field=models.TextField(blank=True, null=True),
        ),
    ]
