# Generated by Django 4.1.4 on 2023-01-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTeam', '0019_userostadmodel_darbare_majmoee'),
    ]

    operations = [
        migrations.AddField(
            model_name='myteammodel',
            name='price5',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
