# Generated by Django 4.1.5 on 2023-01-19 12:57

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTeam', '0022_bokingdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BokingDateDastyar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField()),
                ('time1', models.BooleanField(default=False)),
                ('time2', models.BooleanField(default=False)),
                ('time3', models.BooleanField(default=False)),
                ('user1', models.CharField(max_length=100, null=True)),
                ('user2', models.CharField(max_length=100, null=True)),
                ('user3', models.CharField(max_length=100, null=True)),
                ('phone1', models.CharField(max_length=100, null=True)),
                ('phone2', models.CharField(max_length=100, null=True)),
                ('phone3', models.CharField(max_length=100, null=True)),
                ('service1', models.CharField(max_length=100, null=True)),
                ('service2', models.CharField(max_length=100, null=True)),
                ('service3', models.CharField(max_length=100, null=True)),
                ('employ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyTeam.myteammodel')),
            ],
        ),
    ]
