# Generated by Django 4.1.5 on 2023-01-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyTeam', '0023_bokingdatedastyar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BokingDateDastyar',
        ),
    ]
