# Generated by Django 4.1.4 on 2022-12-13 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=0, verbose_name='price')),
                ('image', models.ImageField(blank=True, upload_to='product/product_cover', verbose_name='Image')),
                ('datetime_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time product create')),
                ('datetime_edit', models.DateTimeField(auto_now=True, verbose_name='time product edit')),
            ],
        ),
    ]
