# Generated by Django 4.1.4 on 2022-12-14 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_comment_recommend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='point',
        ),
    ]
